# optional list of image pull secrets to use to pull images
jx:
  imagePullSecrets:
    - tekton-container-registry-auth


  # these variables are used by 'jx gitops variables' to default environment variables
  # into the .jx/variables.sh file which can be overriden on a pre repository basis
  # or during a pipeline by writing to the '.jx/variables.sh' file
  pipelineVariables: {}
