jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jx3-pipeline-catalog.git
  cluster:
    chartRepository: http://bucketrepo/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    namespace: jx
    provider: kubernetes
    registry: ghcr.io
  environments:
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  gitops: true
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  kaniko: true
  repository: bucketrepo
  secretStorage: local
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: false
      url: ""
    reports:
      enabled: false
      url: ""
    repository:
      enabled: false
      url: ""
  vault: {}
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
