jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: false
